### PR TITLE
Template v1

### PR DESCRIPTION
**Pull request by veselatereza**

### CODE REVIEW

**Review by pajav7 — APPROVED** [review]
:+1:

**Review by b3ken — APPROVED** [review]

**Review by zdenekmaxa — APPROVED** [review]
Look OK, except for

.gitignore should be created / updated to exclude *.pyc files in __pycache__
subsequently, all already checked in *.pyc files shall be removed

does it run as is? we shall make effort to provide a functional template

I think this will be very useful in speeding up the candidates.

I am two minds on providing also test template and hinting towards pytest ... a candidate would have to use it anyway within our ecosystem so I am inclined to providing pytest envelope ...

**Comment by veselatereza** [comment]
@zdenekmaxa thanks for the feedback :)
- we will remove the pyc files
- yes, it run as it is (with docker-compose). Will check again if it works locally but should work fine too
- ok, we can probably hint there pytest. Would you also hint some linter/black?

**Comment by zdenekmaxa** [comment]
> * ok, we can probably hint there pytest. Would you also hint some linter/black?

no, I would not. mainly since it's provision basically means - template does it all.
I would just state in the description and integration with any linting, formatting tool is optional for extra points gain.

**Comment by veselatereza** [comment]
@zdenekmaxa are you find with the last commit for the hint around tests or would you add more hints? (such as how to trigger them etc.)

**Comment by veselatereza** [comment]
I will merge this and if we want to add some changes, let's do it in subsequent PRs :)

**Pull request merged**
